# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74501afe51d9ba165d26212e840faf5c51df042a9538dd5ce1e800a35c9df43e258bd7278064b34da461943c98435427fd5827c1e415e21772a35ddc9b9908b5

test:
  secret_key_base: ff484a265ab8b6e000b15d93a5da744f040d81255b644dc45228e9343b47471949321ed961e861e98aebec35b5ad762b24bdddd9241dd3ef7616c7c0e75eb17c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
